<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SPCOKLAP-5140" failures="0" tests="9" name="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" time="21.973" errors="2" timestamp="2025-03-13T13:59:37 IST" skipped="7">
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="takeScreenshotOnFailure" time="0.163">
    <error message="Cannot invoke &quot;org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)&quot; because &quot;screenshot&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)" because "screenshot" is null
at com.Utility.ScreenShot.takeScreenShot(ScreenShot.java:29)
at core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass.takeScreenshotOnFailure(AlertsPlaceholderManagement_TestClass.java:252)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- takeScreenshotOnFailure -->
  <system-out/>
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Insert_New_Entry_All_Valid_Fields" time="21.810">
    <error message="Cannot invoke &quot;java.sql.Connection.prepareCall(String)&quot; because &quot;conn&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareCall(String)" because "conn" is null
at com.BasePackage.DBUtils.ExecuteAnyOracleSQLStoredProcedure(DBUtils.java:271)
at core.AlertsandNotifications.AlertsPlaceholderManagement_MainClass.prepareAndExecuteInsertQuery(AlertsPlaceholderManagement_MainClass.java:45)
at core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass.Insert_New_Entry_All_Valid_Fields(AlertsPlaceholderManagement_TestClass.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Insert_New_Entry_All_Valid_Fields -->
  <system-out/>
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Successful_Login" time="0.000">
    <skipped/>
  </testcase> <!-- Successful_Login -->
  <system-out/>
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Access_Alerts_and_Notifications" time="0.000">
    <skipped/>
  </testcase> <!-- Access_Alerts_and_Notifications -->
  <system-out/>
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Access_Placeholder_Management" time="0.000">
    <skipped/>
  </testcase> <!-- Access_Placeholder_Management -->
  <system-out/>
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Pagination_Controls_Display" time="0.000">
    <skipped/>
  </testcase> <!-- Pagination_Controls_Display -->
  <system-out/>
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Paginate_to_Next_Page" time="0.000">
    <skipped/>
  </testcase> <!-- Paginate_to_Next_Page -->
  <system-out/>
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Paginate_to_Previous_Page" time="0.000">
    <skipped/>
  </testcase> <!-- Paginate_to_Previous_Page -->
  <system-out/>
  <testcase classname="core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Search_Placeholder" time="0.000">
    <skipped/>
  </testcase> <!-- Search_Placeholder -->
  <system-out/>
</testsuite> <!-- core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass -->
